"""
Database Seeding Script for Smart Waste Collection Travel-Time & Route Simulator.

IMPORTANT RESEARCH NOTICE:
All records generated by this script represent SYNTHETIC DEMO DATA for Phase 2.
No real-world private addresses or personal driver identities are utilized.
"""

from datetime import datetime, date, timedelta
import random
from sqlalchemy.orm import Session
from app.core.database import SessionLocal, engine, Base
from app.models.vehicle import Vehicle
from app.models.driver import Driver
from app.models.route import Route
from app.models.route_stop import RouteStop
from app.models.waste_collection import WasteCollection
from app.models.weather import WeatherCondition
from app.models.traffic import TrafficCondition
from app.models.event import Event
from app.models.road_restriction import RoadRestriction
from app.models.observation import TravelTimeObservation
from app.models.eta_prediction import ETAPrediction
from app.models.scenario import Scenario
from app.models.experiment import Experiment
from app.models.experiment_result import ExperimentResult
from app.models.routing_models import ActiveTrip, RouteCandidate, ReroutingEvent
from app.models.fleet_models import CollectionTask, FleetAuditEvent


def seed_database(db: Session = None) -> dict:
    close_session = False
    if db is None:
        Base.metadata.create_all(bind=engine)
        db = SessionLocal()
        close_session = True

    try:
        # Clear existing data in reverse dependency order
        db.query(FleetAuditEvent).delete()
        db.query(CollectionTask).delete()
        db.query(ReroutingEvent).delete()
        db.query(RouteCandidate).delete()
        db.query(ActiveTrip).delete()
        db.query(ExperimentResult).delete()
        db.query(Experiment).delete()
        db.query(Scenario).delete()


        db.query(ETAPrediction).delete()
        db.query(TravelTimeObservation).delete()
        db.query(RoadRestriction).delete()
        db.query(Event).delete()
        db.query(TrafficCondition).delete()
        db.query(WeatherCondition).delete()
        db.query(WasteCollection).delete()
        db.query(RouteStop).delete()
        db.query(Route).delete()
        db.query(Driver).delete()
        db.query(Vehicle).delete()
        db.commit()

        print("Seeding Phase 2 Synthetic Operational Dataset...")

        # 1. Vehicles (10 vehicles, capacities 5-15 tons)
        vehicles_data = [
            ("V-01", "COMPACTOR_HEAVY", 12.0, "AVAILABLE"),
            ("V-02", "COMPACTOR_MEDIUM", 10.0, "AVAILABLE"),
            ("V-03", "COMPACTOR_HEAVY", 12.0, "IN_SERVICE"),
            ("V-04", "COMPACTOR_LIGHT", 6.0, "AVAILABLE"),
            ("V-05", "COMPACTOR_MEDIUM", 10.0, "AVAILABLE"),
            ("V-06", "COMPACTOR_MEDIUM", 10.0, "AVAILABLE"),
            ("V-07", "COMPACTOR_LIGHT", 8.0, "AVAILABLE"),
            ("V-08", "COMPACTOR_HEAVY", 14.0, "IN_SERVICE"),
            ("V-09", "COMPACTOR_MEDIUM", 10.0, "MAINTENANCE"),
            ("V-10", "RECYCLING_LOADER", 8.0, "AVAILABLE"),
        ]
        vehicles = []
        for code, v_type, cap, status in vehicles_data:
            v = Vehicle(
                vehicle_code=code,
                vehicle_type=v_type,
                capacity_tons=cap,
                status=status,
                active=(status != "UNAVAILABLE"),
            )
            db.add(v)
            vehicles.append(v)
        db.commit()

        # 2. Drivers (15 drivers, max 480 min standard shift)
        drivers_data = [
            ("EMP-001", "Alex Mercer", 480, 210, "ON_DUTY"),
            ("EMP-002", "Elena Vance", 480, 180, "ON_DUTY"),
            ("EMP-003", "Marcus Reed", 480, 320, "ON_DUTY"),
            ("EMP-004", "Sarah Chen", 480, 120, "AVAILABLE"),
            ("EMP-005", "David Kim", 480, 260, "ON_DUTY"),
            ("EMP-006", "Carlos Gomez", 480, 195, "ON_DUTY"),
            ("EMP-007", "Priya Patel", 480, 140, "AVAILABLE"),
            ("EMP-008", "Liam Johnson", 480, 310, "ON_DUTY"),
            ("EMP-009", "Aisha Khan", 480, 90, "AVAILABLE"),
            ("EMP-010", "Mateo Silva", 480, 0, "AVAILABLE"),
            ("EMP-011", "Chloe Martin", 480, 0, "AVAILABLE"),
            ("EMP-012", "Noah Taylor", 480, 150, "ON_DUTY"),
            ("EMP-013", "Grace Hopper", 480, 45, "AVAILABLE"),
            ("EMP-014", "Kenji Sato", 480, 0, "OFF_DUTY"),
            ("EMP-015", "Hannah Abbott", 480, 0, "AVAILABLE"),
        ]
        drivers = []
        for code, name, max_w, cur_w, status in drivers_data:
            d = Driver(
                employee_code=code,
                name=name,
                max_work_minutes_per_shift=max_w,
                current_work_minutes=cur_w,
                status=status,
                active=(status != "OFF_DUTY"),
            )
            db.add(d)
            drivers.append(d)
        db.commit()

        # 3. Weather Conditions (20 records)
        weather_templates = [
            ("CLEAR", 22.5, 0.0, 12.0, "LOW"),
            ("CLEAR", 24.0, 0.0, 10.0, "LOW"),
            ("CLOUDY", 19.0, 0.2, 8.5, "LOW"),
            ("LIGHT_RAIN", 16.5, 2.8, 6.0, "MEDIUM"),
            ("HEAVY_RAIN", 14.0, 18.5, 2.5, "HIGH"),
            ("STORM", 12.0, 35.0, 1.2, "HIGH"),
        ]
        weather_records = []
        base_time = datetime.utcnow() - timedelta(days=7)
        for i in range(20):
            cond, temp, rain, vis, sev = weather_templates[i % len(weather_templates)]
            w = WeatherCondition(
                observation_time=base_time + timedelta(hours=i * 8),
                condition=cond,
                temperature_c=temp + random.uniform(-2, 2),
                rainfall_mm=max(0.0, rain + random.uniform(-0.5, 1.0)),
                visibility_km=max(0.5, vis + random.uniform(-1.0, 1.0)),
                severity=sev,
            )
            db.add(w)
            weather_records.append(w)
        db.commit()

        # 4. Traffic Conditions (20 records)
        traffic_templates = [
            ("LOW", 15.0, 48.0),
            ("LOW", 22.0, 44.0),
            ("MEDIUM", 45.0, 32.0),
            ("MEDIUM", 55.0, 26.0),
            ("HIGH", 78.0, 16.0),
            ("SEVERE", 92.0, 9.5),
        ]
        traffic_records = []
        for i in range(20):
            t_level, cong, spd = traffic_templates[i % len(traffic_templates)]
            tr = TrafficCondition(
                observation_time=base_time + timedelta(hours=i * 8),
                traffic_level=t_level,
                congestion_index=min(100.0, max(0.0, cong + random.uniform(-3, 3))),
                average_speed_kmh=max(5.0, spd + random.uniform(-2, 2)),
            )
            db.add(tr)
            traffic_records.append(tr)
        db.commit()

        # 5. Events (10 records)
        events_data = [
            ("Downtown Cultural Arts Parade", "PARADE", 40.7180, -73.9980, 2.5, "MEDIUM"),
            ("City Arena Basketball Derby", "SPORTS", 40.7505, -73.9934, 1.8, "HIGH"),
            ("Riverside Food Festival", "FESTIVAL", 40.7250, -74.0090, 1.2, "LOW"),
            ("Civic Plaza Marathon Stage", "CIVIC", 40.7128, -74.0060, 3.0, "HIGH"),
            ("Metropolitan Charity Concert", "CONCERT", 40.7380, -73.9800, 1.5, "MEDIUM"),
        ]
        event_records = []
        for i, (name, e_type, lat, lng, rad, imp) in enumerate(events_data * 2):
            ev = Event(
                event_name=f"{name} #{i+1}",
                event_type=e_type,
                start_time=base_time + timedelta(days=i, hours=10),
                end_time=base_time + timedelta(days=i, hours=16),
                latitude=lat + random.uniform(-0.005, 0.005),
                longitude=lng + random.uniform(-0.005, 0.005),
                impact_radius_km=rad,
                impact_level=imp,
            )
            db.add(ev)
            event_records.append(ev)
        db.commit()

        # 6. Road Restrictions (10 records)
        restrictions_data = [
            ("PARTIAL_CLOSURE", "Water pipe replacement on 4th Ave", 40.7280, -73.9910, 0.6, "MEDIUM"),
            ("CONSTRUCTION", "Asphalt resurfacing work on Broadway", 40.7200, -74.0010, 1.0, "HIGH"),
            ("LANE_RESTRICTION", "Bridge maintenance outer curb lane", 40.7080, -73.9990, 0.8, "LOW"),
            ("ROAD_CLOSURE", "Emergency utility line repair", 40.7350, -73.9850, 0.4, "HIGH"),
            ("LANE_RESTRICTION", "Tree trimming and street sweeping", 40.7420, -73.9780, 0.5, "LOW"),
        ]
        restriction_records = []
        for i, (r_type, desc, lat, lng, rad, sev) in enumerate(restrictions_data * 2):
            rr = RoadRestriction(
                restriction_type=r_type,
                description=f"{desc} (Zone {i+1})",
                start_time=base_time + timedelta(days=i),
                end_time=base_time + timedelta(days=i + 2),
                latitude=lat,
                longitude=lng,
                affected_radius_km=rad,
                severity=sev,
                active=(i % 3 != 0),
            )
            db.add(rr)
            restriction_records.append(rr)
        db.commit()

        # 7. Routes & Stops (10 routes with >= 5 stops each)
        routes_spec = [
            ("R-101", 0, 0, 18.5, 4.2, 42.0, 49.0, "On Schedule"),
            ("R-102", 1, 1, 14.2, 3.8, 35.0, 39.0, "On Schedule"),
            ("R-103", 2, 2, 22.8, 5.9, 52.0, 68.0, "Delayed"),
            ("R-104", 3, 3, 11.0, 2.1, 28.0, 30.0, "On Schedule"),
            ("R-105", 4, 4, 19.4, 5.1, 48.0, 59.0, "At Risk"),
            ("R-106", 5, 5, 16.8, 4.6, 40.0, 44.0, "On Schedule"),
            ("R-107", 6, 6, 13.5, 3.4, 32.0, 35.0, "On Schedule"),
            ("R-108", 7, 7, 21.0, 4.9, 50.0, 64.0, "Delayed"),
            ("R-109", 1, 8, 17.2, 4.0, 39.0, 43.0, "On Schedule"),
            ("R-110", 3, 9, 15.0, 3.5, 34.0, 37.0, "On Schedule"),
        ]

        # Waypoint coordinate bases around NY coordinates
        coord_bases = [
            (40.7128, -74.0060),
            (40.7180, -73.9980),
            (40.7250, -73.9920),
            (40.7310, -73.9850),
            (40.7380, -73.9800),
            (40.7450, -73.9720),
        ]

        routes = []
        all_stops = []
        for code, v_idx, d_idx, dist, waste, base_eta, act_eta, status in routes_spec:
            r = Route(
                route_code=code,
                vehicle_id=vehicles[v_idx].id,
                driver_id=drivers[d_idx].id,
                route_date=date.today(),
                start_time=datetime.utcnow() - timedelta(hours=3),
                end_time=datetime.utcnow() if status != "IN_PROGRESS" else None,
                total_distance_km=dist,
                total_waste_tons=waste,
                baseline_eta_minutes=base_eta,
                actual_duration_minutes=act_eta,
                status=status,
            )
            db.add(r)
            db.flush()
            routes.append(r)

            # Generate 6 RouteStops and WasteCollections for each Route
            for seq, (c_lat, c_lng) in enumerate(coord_bases, start=1):
                stop_waste = round(waste / 5.0 if seq > 1 and seq < 6 else 0.0, 2)
                stop = RouteStop(
                    route_id=r.id,
                    stop_sequence=seq,
                    latitude=c_lat + (v_idx * 0.002),
                    longitude=c_lng + (v_idx * 0.002),
                    waste_tons=stop_waste,
                    service_minutes=6.0 if stop_waste > 0 else 2.0,
                    completed=(seq <= 3),
                )
                db.add(stop)
                db.flush()
                all_stops.append(stop)

                if stop_waste > 0:
                    wc = WasteCollection(
                        route_id=r.id,
                        stop_id=stop.id,
                        collection_date=date.today(),
                        waste_tons=stop_waste,
                        waste_type="GENERAL" if seq % 2 == 0 else "RECYCLABLE",
                    )
                    db.add(wc)
        db.commit()

        # 8. Travel Time Observations (60 records)
        observations = []
        for i in range(60):
            r = routes[i % len(routes)]
            w_rec = weather_records[i % len(weather_records)]
            tr_rec = traffic_records[i % len(traffic_records)]
            ev_rec = event_records[i % len(event_records)] if i % 3 == 0 else None
            rr_rec = restriction_records[i % len(restriction_records)] if i % 4 == 0 else None

            # Realistic synthetic correlation factor:
            # Baseline is distance * constant speed (25 km/h -> 2.4 min/km)
            base_time_calc = round(r.total_distance_km * 2.2 + 10.0, 1)

            # Weather penalty
            weather_mult = 1.0
            if w_rec.condition in ["LIGHT_RAIN"]:
                weather_mult = 1.15
            elif w_rec.condition in ["HEAVY_RAIN", "STORM"]:
                weather_mult = 1.45

            # Traffic penalty
            traffic_mult = 1.0 + (tr_rec.congestion_index / 150.0)

            # Event / road restriction penalty
            event_add = 6.0 if ev_rec else 0.0
            rr_add = 8.0 if rr_rec and rr_rec.active else 0.0

            actual_time_calc = round(base_time_calc * weather_mult * traffic_mult + event_add + rr_add, 1)

            obs = TravelTimeObservation(
                route_id=r.id,
                observation_date=date.today() - timedelta(days=i % 14),
                distance_km=r.total_distance_km,
                baseline_travel_minutes=base_time_calc,
                actual_travel_minutes=actual_time_calc,
                weather_id=w_rec.id,
                traffic_id=tr_rec.id,
                event_id=ev_rec.id if ev_rec else None,
                road_restriction_id=rr_rec.id if rr_rec else None,
                waste_volume_tons=r.total_waste_tons,
                hour_of_day=(7 + (i * 2)) % 24,
                day_of_week=i % 7,
            )
            db.add(obs)
            observations.append(obs)
        db.commit()

        # 9. ETA Predictions (30 records: BASELINE and CONTEXT_AWARE pairs)
        for i in range(15):
            r = routes[i % len(routes)]
            act_dur = r.actual_duration_minutes or 45.0
            base_pred = r.baseline_eta_minutes
            ctx_pred = round(act_dur - random.uniform(-2.0, 2.0), 1)

            # Baseline Prediction Record
            p1 = ETAPrediction(
                route_id=r.id,
                prediction_time=datetime.utcnow() - timedelta(hours=i * 3),
                model_type="BASELINE",
                predicted_eta_minutes=base_pred,
                actual_eta_minutes=act_dur,
                absolute_error_minutes=round(abs(act_dur - base_pred), 1),
            )
            db.add(p1)

            # Context-Aware Prediction Record
            p2 = ETAPrediction(
                route_id=r.id,
                prediction_time=datetime.utcnow() - timedelta(hours=i * 3),
                model_type="CONTEXT_AWARE",
                predicted_eta_minutes=ctx_pred,
                actual_eta_minutes=act_dur,
                absolute_error_minutes=round(abs(act_dur - ctx_pred), 1),
            )
            db.add(p2)
        db.commit()

        # 10. Scenarios (5 Scenarios)
        scenarios_data = [
            ("Normal Conditions", "Clear", "Low", "None", "None", "Normal", "Morning", "Standard baseline weather with nominal road access"),
            ("Heavy Rain", "Heavy Rain", "Medium", "None", "None", "Normal", "Morning", "Monsoon precipitation with low visibility and wet road friction"),
            ("Major Event", "Clear", "High", "Major Event", "None", "Normal", "Evening", "Stadium athletic match with localized pedestrian surge"),
            ("Road Closure", "Clear", "High", "None", "Full Closure", "Normal", "Afternoon", "Emergency arterial closure and detour congestion"),
            ("High Waste Volume", "Clear", "Low", "None", "None", "Extreme", "Morning", "Post-festival container overflow with elevated stop dwell time"),
        ]
        scenarios = []
        for name, w_cond, tr_lvl, ev_lvl, rr_lvl, wv_lvl, tod, desc in scenarios_data:
            sc = Scenario(
                scenario_name=name,
                weather_condition=w_cond,
                traffic_level=tr_lvl,
                event_level=ev_lvl,
                road_restriction_level=rr_lvl,
                waste_volume_level=wv_lvl,
                time_of_day=tod,
                description=desc,
            )
            db.add(sc)
            scenarios.append(sc)
        db.commit()

        # 11. Experiments & Results (5 experiments, 10 results)
        benchmarks = [
            (6.8, 1.9, 8.5, 2.8, 92.5),
            (14.2, 3.5, 18.1, 4.9, 88.0),
            (16.5, 4.1, 21.0, 5.6, 86.5),
            (19.8, 5.2, 24.3, 7.1, 84.0),
            (11.4, 2.7, 14.8, 3.9, 91.0),
        ]

        for i, sc in enumerate(scenarios):
            exp = Experiment(
                experiment_name=f"Validation Benchmark: {sc.scenario_name}",
                description=f"Automated evaluation across historical and simulated stress vectors ({sc.scenario_name})",
                scenario_id=sc.id,
                started_at=datetime.utcnow() - timedelta(days=5 - i),
                completed_at=datetime.utcnow() - timedelta(days=5 - i, hours=-2),
                status="COMPLETED",
            )
            db.add(exp)
            db.flush()

            b_mae, c_mae, b_rmse, c_rmse, tol = benchmarks[i]

            # Baseline Result
            r_base = ExperimentResult(
                experiment_id=exp.id,
                model_type="BASELINE",
                mae=b_mae,
                rmse=b_rmse,
                mean_error=round(b_mae * 1.1, 1),
                median_error=round(b_mae * 0.95, 1),
                within_tolerance_percent=round(tol * 0.65, 1),
                route_completion_minutes=55.0,
            )
            db.add(r_base)

            # Context Aware Result
            r_ctx = ExperimentResult(
                experiment_id=exp.id,
                model_type="CONTEXT_AWARE",
                mae=c_mae,
                rmse=c_rmse,
                mean_error=round(c_mae * 1.05, 1),
                median_error=round(c_mae * 0.9, 1),
                within_tolerance_percent=tol,
                route_completion_minutes=48.0,
            )
            db.add(r_ctx)

        # Seed Phase 7 Collection Tasks & Audit Events
        initial_tasks = [
            CollectionTask(
                id="TSK-DEMO-01",
                location_node="COLLECTION_ZONE_A",
                estimated_waste_kg=1200.0,
                priority="NORMAL",
                request_type="SCHEDULED_COLLECTION",
                status="ASSIGNED",
                assigned_vehicle_id="V-01",
                assigned_driver_id="EMP-001",
                notes="Morning commercial pickup",
                created_at=datetime.utcnow() - timedelta(hours=2),
                assigned_at=datetime.utcnow() - timedelta(hours=1),
            ),
            CollectionTask(
                id="TSK-DEMO-02",
                location_node="COLLECTION_ZONE_B",
                estimated_waste_kg=1500.0,
                priority="NORMAL",
                request_type="SCHEDULED_COLLECTION",
                status="ASSIGNED",
                assigned_vehicle_id="V-01",
                assigned_driver_id="EMP-001",
                notes="Midtown secondary collection",
                created_at=datetime.utcnow() - timedelta(hours=2),
                assigned_at=datetime.utcnow() - timedelta(hours=1),
            ),
            CollectionTask(
                id="TSK-DEMO-03",
                location_node="COLLECTION_ZONE_E",
                estimated_waste_kg=1100.0,
                priority="NORMAL",
                request_type="SCHEDULED_COLLECTION",
                status="IN_PROGRESS",
                assigned_vehicle_id="V-02",
                assigned_driver_id="EMP-002",
                notes="West waterfront commercial waste",
                created_at=datetime.utcnow() - timedelta(hours=1),
                assigned_at=datetime.utcnow() - timedelta(minutes=45),
            ),
            CollectionTask(
                id="TSK-DEMO-04",
                location_node="COLLECTION_ZONE_C",
                estimated_waste_kg=2200.0,
                priority="HIGH",
                request_type="SCHEDULED_COLLECTION",
                status="PENDING",
                notes="High-density mixed use hub",
                created_at=datetime.utcnow() - timedelta(minutes=30),
            ),
            CollectionTask(
                id="TSK-DEMO-05",
                location_node="COLLECTION_ZONE_D",
                estimated_waste_kg=1400.0,
                priority="NORMAL",
                request_type="SCHEDULED_COLLECTION",
                status="PENDING",
                notes="North residential sector",
                created_at=datetime.utcnow() - timedelta(minutes=20),
            ),
            CollectionTask(
                id="TSK-DEMO-EMG",
                location_node="COLLECTION_ZONE_F",
                estimated_waste_kg=1800.0,
                priority="URGENT",
                request_type="EMERGENCY_REQUEST",
                status="PENDING",
                deadline_minutes=45.0,
                notes="Overflowing commercial dumpsters requiring rapid dispatch",
                created_at=datetime.utcnow() - timedelta(minutes=5),
            ),
        ]
        for task in initial_tasks:
            db.add(task)

        init_audit = FleetAuditEvent(
            id="AUD-INIT-001",
            event_type="FLEET_INITIALIZED",
            task_id="TSK-DEMO-01",
            previous_vehicle_id=None,
            new_vehicle_id="V-01",
            previous_route=[],
            new_route=["DEPOT_CENTRAL", "COLLECTION_ZONE_A", "COLLECTION_ZONE_B", "LANDFILL_MAIN"],
            predicted_eta_before=None,
            predicted_eta_after=24.5,
            distance_difference_km=7.5,
            safety_result="SAFE",
            selected_eta_model="ADAPTIVE_HYBRID",
            reason="Nominal morning dispatch: V-01 selected with optimal payload balance.",
            timestamp=datetime.utcnow() - timedelta(hours=1),
        )
        db.add(init_audit)

        db.commit()

        summary = {
            "vehicles": len(vehicles),
            "drivers": len(drivers),
            "routes": len(routes),
            "route_stops": len(all_stops),
            "weather_records": len(weather_records),
            "traffic_records": len(traffic_records),
            "events": len(event_records),
            "road_restrictions": len(restriction_records),
            "observations": len(observations),
            "scenarios": len(scenarios),
            "status": "success",
        }
        print(f"Seeding completed successfully: {summary}")
        return summary

    finally:
        if close_session:
            db.close()


if __name__ == "__main__":
    seed_database()
