"""add_phase7_fleet_models

Revision ID: cb5e4bcd9a63
Revises: 001_initial
Create Date: 2026-09-06 16:35:49.234988

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5e4bcd9a63'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_trips',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=64), nullable=False),
    sa.Column('origin_node', sa.String(length=64), nullable=False),
    sa.Column('destination_node', sa.String(length=64), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=False),
    sa.Column('visited_nodes', sa.JSON(), nullable=False),
    sa.Column('remaining_stops', sa.JSON(), nullable=False),
    sa.Column('current_path', sa.JSON(), nullable=False),
    sa.Column('current_payload_kg', sa.Float(), nullable=False),
    sa.Column('vehicle_capacity_kg', sa.Float(), nullable=False),
    sa.Column('elapsed_time_minutes', sa.Float(), nullable=False),
    sa.Column('max_shift_hours', sa.Float(), nullable=False),
    sa.Column('distance_traveled_km', sa.Float(), nullable=False),
    sa.Column('current_eta_minutes', sa.Float(), nullable=False),
    sa.Column('baseline_eta_minutes', sa.Float(), nullable=False),
    sa.Column('hybrid_eta_minutes', sa.Float(), nullable=False),
    sa.Column('eta_uncertainty_minutes', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active_disruptions', sa.JSON(), nullable=False),
    sa.Column('reroute_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_payload_kg >= 0', name='check_active_trip_payload'),
    sa.CheckConstraint('elapsed_time_minutes >= 0', name='check_active_trip_elapsed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_trips_id'), 'active_trips', ['id'], unique=False)
    op.create_table('collection_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('location_node', sa.String(length=64), nullable=False),
    sa.Column('estimated_waste_kg', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_driver_id', sa.String(length=64), nullable=True),
    sa.Column('deadline_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('estimated_waste_kg >= 0', name='check_positive_task_waste'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_tasks_assigned_driver_id'), 'collection_tasks', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_collection_tasks_assigned_vehicle_id'), 'collection_tasks', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_collection_tasks_id'), 'collection_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_collection_tasks_location_node'), 'collection_tasks', ['location_node'], unique=False)
    op.create_table('fleet_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('previous_vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('new_vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('previous_route', sa.JSON(), nullable=False),
    sa.Column('new_route', sa.JSON(), nullable=False),
    sa.Column('predicted_eta_before', sa.Float(), nullable=True),
    sa.Column('predicted_eta_after', sa.Float(), nullable=True),
    sa.Column('distance_difference_km', sa.Float(), nullable=False),
    sa.Column('safety_result', sa.String(length=30), nullable=False),
    sa.Column('selected_eta_model', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_audit_events_id'), 'fleet_audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_fleet_audit_events_task_id'), 'fleet_audit_events', ['task_id'], unique=False)
    op.create_table('rerouting_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_details', sa.JSON(), nullable=False),
    sa.Column('previous_path', sa.JSON(), nullable=False),
    sa.Column('new_path', sa.JSON(), nullable=False),
    sa.Column('previous_eta_minutes', sa.Float(), nullable=False),
    sa.Column('new_eta_minutes', sa.Float(), nullable=False),
    sa.Column('time_saved_minutes', sa.Float(), nullable=False),
    sa.Column('distance_difference_km', sa.Float(), nullable=False),
    sa.Column('selected_candidate_id', sa.String(length=64), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('decision_rationale', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['active_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rerouting_events_id'), 'rerouting_events', ['id'], unique=False)
    op.create_index(op.f('ix_rerouting_events_trip_id'), 'rerouting_events', ['trip_id'], unique=False)
    op.create_table('route_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('path', sa.JSON(), nullable=False),
    sa.Column('path_coordinates', sa.JSON(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('predicted_eta_minutes', sa.Float(), nullable=False),
    sa.Column('baseline_eta_minutes', sa.Float(), nullable=False),
    sa.Column('hybrid_eta_minutes', sa.Float(), nullable=False),
    sa.Column('eta_uncertainty_minutes', sa.Float(), nullable=False),
    sa.Column('safety_valid', sa.Boolean(), nullable=False),
    sa.Column('safety_violations', sa.JSON(), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['active_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_candidates_id'), 'route_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_route_candidates_trip_id'), 'route_candidates', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_candidates_trip_id'), table_name='route_candidates')
    op.drop_index(op.f('ix_route_candidates_id'), table_name='route_candidates')
    op.drop_table('route_candidates')
    op.drop_index(op.f('ix_rerouting_events_trip_id'), table_name='rerouting_events')
    op.drop_index(op.f('ix_rerouting_events_id'), table_name='rerouting_events')
    op.drop_table('rerouting_events')
    op.drop_index(op.f('ix_fleet_audit_events_task_id'), table_name='fleet_audit_events')
    op.drop_index(op.f('ix_fleet_audit_events_id'), table_name='fleet_audit_events')
    op.drop_table('fleet_audit_events')
    op.drop_index(op.f('ix_collection_tasks_location_node'), table_name='collection_tasks')
    op.drop_index(op.f('ix_collection_tasks_id'), table_name='collection_tasks')
    op.drop_index(op.f('ix_collection_tasks_assigned_vehicle_id'), table_name='collection_tasks')
    op.drop_index(op.f('ix_collection_tasks_assigned_driver_id'), table_name='collection_tasks')
    op.drop_table('collection_tasks')
    op.drop_index(op.f('ix_active_trips_id'), table_name='active_trips')
    op.drop_table('active_trips')
    # ### end Alembic commands ###
